name: tests
on:
  push:
    branches: ['v*']
  pull_request:
defaults:
  run:
    shell: bash
    working-directory: .
env:
  cargo_hack_flags: >
    --all-features
jobs:
  miri:
    name: "Miri"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        we: [le, be]
        include:
        - we: be
          cc: --target s390x-unknown-linux-gnu
        - we: le
          cc: --target x86_64-unknown-linux-gnu
    steps:
      - uses: taiki-e/checkout-action@v1
      - uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ matrix.we }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Miri
        run: |
          rustup toolchain install nightly \
            --profile minimal \
            -c miri \
            ${{ matrix.cc }} \
            --no-self-update
          rustup override set nightly
          cargo miri setup
      - name: Test with Miri
        run: cargo miri test --workspace --all-features ${{ matrix.cc }}
  checks:
    name: "Checks"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        tc: ["1.91", "stable", "beta", "nightly"]
        include:
        - tc: stable
        - tc: beta
        - tc: nightly
        - os: ubuntu-latest
          cc: "-t \
            aarch64-linux-android,\
            i686-pc-windows-gnu,\
            i686-unknown-linux-gnu,\
            x86_64-unknown-illumos,\
            i686-unknown-freebsd,\
            x86_64-unknown-redox"
        - os: macos-latest
          cc: "-t \
            aarch64-apple-ios,\
            x86_64-apple-darwin,\
            wasm32-wasip1,\
            wasm32-wasip2,\
            wasm32-unknown-unknown"
    steps:
      - uses: taiki-e/checkout-action@v1
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-hack
      - uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ matrix.tc }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Rust
        run: |
          rustup toolchain install ${{ matrix.tc }} \
            --profile minimal \
            -c clippy,rustfmt \
            ${{ matrix.cc }} \
            --no-self-update
          rustup override set ${{ matrix.tc }}
      - name: Check code formatting
        run: cargo fmt --check
      - name: Checking clippy for warnings
        run: |
          cargo hack build --workspace --all-targets $cargo_hack_flags
          cargo hack clippy --workspace --all-targets $cargo_hack_flags -- \
            -D warnings
      - if: ${{ matrix.cc }}
        name: Checking cross-compilation works
        run: |
          for target in $(echo ${{ matrix.cc }} | sed 's/-t //g' | sed 's/,/ /g')
          do
            cargo hack build --workspace "--target=$target" $cargo_hack_flags
            cargo hack clippy --workspace "--target=$target" $cargo_hack_flags \
              -- -D warnings
          done
      - name: Check doc generation succeeds
        run: cargo doc --all-features --no-deps
      - name: Running tests
        run: cargo hack test --workspace $cargo_hack_flags
